// examples/casino/expo/src/App.tsx
import {
  CasinoProgram,
  casinoScreen,
  emptyModel,
  messageFromToken,
} from 'casino-core-example'
import { useState } from 'react'
import { SafeAreaProvider, SafeAreaView } from 'react-native-safe-area-context'

import { paintScreen } from './paintScreen.js'

/** Draws one Casino window from the Program screen tree. */
export const App = () => {
  const [model, setModel] = useState(emptyModel)
  const sendToken = (token: string) => {
    const message = messageFromToken(token, model)
    if (message === undefined) {
      return
    }
    setModel(CasinoProgram.update(model, message)[0])
  }
  return (
    <SafeAreaProvider>
      <SafeAreaView style={{ backgroundColor: '#ffffff', flex: 1 }}>
        {paintScreen(casinoScreen(model), sendToken)}
      </SafeAreaView>
    </SafeAreaProvider>
  )
}

// examples/casino/svelte/src/App.svelte
<script lang="ts">
  import {
    CasinoProgram,
    emptyModel,
    messageFromToken,
    casinoScreen,
  } from 'casino-core-example'

  import PaintScreen from './PaintScreen.svelte'

  let model = $state(emptyModel())
  const screen = $derived(casinoScreen(model))

  const sendToken = (token: string) => {
    const message = messageFromToken(token, model)
    if (message === undefined) {
      return
    }
    model = CasinoProgram.update(model, message)[0]
  }
</script>

<main>
  <PaintScreen node={screen} {sendToken} />
</main>
