// examples/counter/svelte/src/App.svelte
<script lang="ts">
  import { useActions, useModel } from './processor.js'

  const counterUri = '/counter'
  const view = $derived(useModel(counterUri))
  const actions = $derived(useActions(counterUri))
</script>

<main>
  {#if view._tag === 'StartingWindow'}
    <section>
      <p>Starting Instant Counter…</p>
    </section>
  {:else if view._tag === 'FailedWindow'}
    <section>
      <p>{view.error}</p>
      <button onclick={() => actions.signIn()} type="button">Sign in</button>
    </section>
  {:else}
    <section>
      <div class="count">{view.count}</div>
      <div class="row">
        <button onclick={() => actions.clickedDecrement()} type="button">
          -
        </button>
        {#if view.count !== 0}
          <button onclick={() => actions.clickedReset()} type="button">
            Reset
          </button>
        {:else}
          <div></div>
        {/if}
        <button onclick={() => actions.clickedIncrement()} type="button">
          +
        </button>
      </div>
    </section>
  {/if}
</main>

// examples/counters/vue/src/App.vue
<script lang="ts" setup>
import { computed, ref } from 'vue'

import { useActions, useModel } from './processor.js'

const listUri = '/counters'

const counterUri = (counterId: string): string => `/counters/${counterId}`

const uri = ref(listUri)
const view = useModel(uri)
const actions = useActions(uri)

const openCounter = (counterId: string) => {
  actions.value.open(counterId)
  uri.value = counterUri(counterId)
}

const goBack = () => {
  actions.value.back()
  uri.value = listUri
}

const isReadyDetail = computed(() => {
  const snapshot = view.value
  if (snapshot._tag !== 'ReadyWindow') {
    return false
  }
  return snapshot.selectedId !== undefined && snapshot.count !== undefined
})
</script>

<template>
  <main>
    <p>FOLDKIT COUNTERS</p>
    <h1>Vue</h1>
    <p v-if="view._tag === 'StartingWindow'">
      Starting Instant Multiple Counters…
    </p>
    <template v-else-if="view._tag === 'FailedWindow'">
      <p role="alert">{{ view.error }}</p>
      <button type="button" @click="actions.signIn">Sign in with Access</button>
    </template>
    <template v-else-if="view._tag === 'ReadyWindow' && isReadyDetail">
      <p>{{ view.selectedId }}</p>
      <p>{{ view.count }}</p>
      <button type="button" @click="actions.increment">+</button>
      <button type="button" @click="actions.decrement">-</button>
      <button type="button" @click="actions.reset">Reset</button>
      <button type="button" @click="actions.showFact">Fact</button>
      <button type="button" @click="goBack">Back</button>
    </template>
    <template v-else-if="view._tag === 'ReadyWindow'">
      <button type="button" @click="actions.addCounter">Add counter</button>
      <article v-for="counter in view.counters" :key="counter.id">
        <button type="button" @click="openCounter(counter.id)">
          {{ counter.id }}
        </button>
        <strong>{{ counter.count }}</strong>
      </article>
    </template>
  </main>
</template>
